//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRealm.Utilities.PdfTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRealm.Utilities.PdfTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright 2010 wkhtmltopdf authors
        /// *
        /// * This file is part of wkhtmltopdf.
        /// *
        /// * wkhtmltopdf is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU Lesser General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * wkhtmltopdf is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dllbegin {
            get {
                return ResourceManager.GetString("dllbegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright 2010 wkhtmltopdf authors
        /// *
        /// * This file is part of wkhtmltopdf.
        /// *
        /// * wkhtmltopdf is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU Lesser General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * wkhtmltopdf is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dllend {
            get {
                return ResourceManager.GetString("dllend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright 2010 wkhtmltopdf authors
        /// *
        /// * This file is part of wkhtmltopdf.
        /// *
        /// * wkhtmltopdf is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU Lesser General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * wkhtmltopdf is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright 2010 wkhtmltopdf authors
        /// *
        /// * This file is part of wkhtmltopdf.
        /// *
        /// * wkhtmltopdf is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU Lesser General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * wkhtmltopdf is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wkhtmltoimage {
            get {
                object obj = ResourceManager.GetObject("wkhtmltoimage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wkhtmltopdf {
            get {
                object obj = ResourceManager.GetObject("wkhtmltopdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wkhtmltox {
            get {
                object obj = ResourceManager.GetObject("wkhtmltox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wkhtmltoxlib {
            get {
                object obj = ResourceManager.GetObject("wkhtmltoxlib", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
